name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  DEV:
    runs-on: ubuntu-latest
    environment: secret_key

    env:
      PORT: ${{ vars.PORT }}
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test ENV output
        run: |
          echo "===TEST==="
          echo "PORT is: ${{ vars.PORT }}"
          echo "MONGODB_URI is: ${{ secrets.MONGODB_URI }}"
          echo "===TEST==="

          echo "PORT is: $PORT"
          echo "MONGODB_URI is: $MONGODB_URI"
          echo "SECRET_KEY is: $SECRET_KEY"
