name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  secret_key:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test ENV output
        run: |
          echo "===TEST==="
          echo "PORT is: ${{ vars.PORT }}"
          echo "MONGODB_URI is: ${{ secrets.MONGODB_URI }}"
          echo "===TEST==="
