name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # Load environment variables here
    env:
      PORT: ${{ vars.PORT }}
      MONGODB_URI: ${{ secrets.MONGODB_URI }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test ENV output
        run: |
          echo "===TEST==="
          echo "PORT is: $PORT"
          echo "MONGODB_URI is: $MONGODB_URI"
          echo "===TEST==="
